#lang info
(define collection "mupdf-drracket-plugin")
(define deps '("base" "git://github.com/Antigen-1/racket-mupdf.git" "quickscript" "gui-lib"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/mupdf-drracket-plugin.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(zhanghao))
(define license '(Apache-2.0 OR MIT))
(define racket-launcher-names '("display-pdf"))
(define racket-launcher-libraries (list (build-path "scripts" "display.rkt")))
